### PR TITLE
Added setWindowOpen and setBoost

### PR DESCRIPTION
**Pull request by wetzf**
Added setWindowOpen (Fritz!DECT 300/301)
It was added to fritzapi in https://github.com/andig/fritzapi/pull/40 but it seems the changes are not yet available via npm.

### CODE REVIEW

**Comment by wetzf** [comment]
I added setBoost as well. It may help @CityJumperAC with his issue #31 
For testing i replaced _.node-red/node_modules/fritzapi/index.js_ with https://github.com/andig/fritzapi/blob/56245fb7f3bd6a5a3940d13ae9db8e9687045067/index.js

**Review by dnknth — COMMENTED** [review]
Looks good, but I wonder whether a time interval in minutes makes more sense from a usability point of view. What do you think?

**Comment by wetzf** [comment]
I thought about that as well. But it made no difference to my usecase, since I am calculating the values in a function anyway. So I used what fritzapi expects.
But I agree that using minutes would be more intuitive. Should the return value be in minutes as well?

**Comment by CityJumperAC** [comment]
Woohoo, i will start testing it in a few minutes! But looks promissing

-> test done, workls like expected.
Will give further feedback tomorrow, after moning boost ;-)

HAPPY NEW YEAR :-)

**Review by dnknth — COMMENTED** [review]
LGTM, reached out to @andig for a published version of andig/fritzapi#40 on NPM.

**Pull request merged**
