### PR TITLE
Wait for initialization, missing commands added, sample flow added

### PR DESCRIPTION
**Pull request by srg64**
Hi Daniel,

thanks for your fritzapi nodes, I like them a lot!

My changes are all related to the thermostat node:
- the thermostat node is now waiting till the initialization of the connection to the fritz box is finished.
- all commands, which are useful in the context of thermostat node, are supported now
- getSessionId is not supported, because I had problems with it and it is not really useful
- getDeviceListFiltered is not supported, because it is easier to use node-red for the filtering
- setTempComfort and setTempNight are removed, because they could never be functional as they are not supported by fritzapi
- there is now a documented sample flow which covers all use cases of the thermostat node

Issues
- getPresence returns wrong results, because of a bug in the fritzapi package. Conversion from number to boolean needs a bugfix.

Best Regards and schöne Ostern,

Stefan

### CODE REVIEW

**Comment by dnknth** [comment]
Thank you / Herzlichen Dank, 

I merged them now. Will publish to NPM tomorrow after testing for regressions.
Thanks for your contribution!

Schöne Ostertage,

    Daniel

**Comment by dnknth** [comment]
Hello @srg64 ,

The changes are now published to NPM as 0.2.10.

I needed to revert one of your changes which broke `setTempNight` and `setTempComfort`.
Currently, there are no corresponding API calls in `fritzapi`, and one of your changes caused exceptions. 

The thermostat calls should probably be named `setTempToNight` and `setTempToComfort` for clarity, but people (like me) are probably using them already, and the documentation also is clear on what the do: They set the **target** temperature to day / night level, rather than adjusting the presets.

**Comment by srg64** [comment]
Hi,

I understand that compatibility is an important topic, so it's fine for 
me to let |setTempNight| and |setTempComfort| remain in the interface.

Regarding the documentation I disagree.
The documentation was completely misleading to me. My understanding was 
completely wrong.

Could you explain the purpose and difference between the three setTemp* 
functions?
There should be a separate section in the documentation about them.

Best Regards,
Stefan


Am 12.04.2020 um 17:43 schrieb dnknth:

**Comment by dnknth** [comment]
Added some remarks for clarification, adjusted HTML labels, published 0.2.11.

**Pull request merged**
